global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'jarvis-api'
    static_configs:
      - targets: ['jarvis-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'jarvis-worker'
    static_configs:
      - targets: ['jarvis-worker:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['jarvis-db:9187']
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['jarvis-redis:9121']
    scrape_interval: 10s